version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass application
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_PASSWORD=application

networks:
  default:
    driver: bridge